"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CircleService = exports.PolygonService = exports.TriangleService = exports.LineService = exports.PointService = exports.Cricle = exports.Polygon = exports.Rectangle = exports.Triangle = exports.Line = exports.Point = void 0;
var point_entity_1 = require("./entities/point.entity");
Object.defineProperty(exports, "Point", { enumerable: true, get: function () { return point_entity_1.Point; } });
var line_entity_1 = require("./entities/line.entity");
Object.defineProperty(exports, "Line", { enumerable: true, get: function () { return line_entity_1.Line; } });
var triangle_entity_1 = require("./entities/triangle.entity");
Object.defineProperty(exports, "Triangle", { enumerable: true, get: function () { return triangle_entity_1.Triangle; } });
var rectangle_entity_1 = require("./entities/rectangle.entity");
Object.defineProperty(exports, "Rectangle", { enumerable: true, get: function () { return rectangle_entity_1.Rectangle; } });
var polygon_entity_1 = require("./entities/polygon.entity");
Object.defineProperty(exports, "Polygon", { enumerable: true, get: function () { return polygon_entity_1.Polygon; } });
var cricle_entity_1 = require("./entities/cricle.entity");
Object.defineProperty(exports, "Cricle", { enumerable: true, get: function () { return cricle_entity_1.Cricle; } });
var point_service_1 = require("./services/point.service");
Object.defineProperty(exports, "PointService", { enumerable: true, get: function () { return point_service_1.PointService; } });
var line_service_1 = require("./services/line.service");
Object.defineProperty(exports, "LineService", { enumerable: true, get: function () { return line_service_1.LineService; } });
var triangle_service_1 = require("./services/triangle.service");
Object.defineProperty(exports, "TriangleService", { enumerable: true, get: function () { return triangle_service_1.TriangleService; } });
var polygon_service_1 = require("./services/polygon.service");
Object.defineProperty(exports, "PolygonService", { enumerable: true, get: function () { return polygon_service_1.PolygonService; } });
var circle_service_1 = require("./services/circle.service");
Object.defineProperty(exports, "CircleService", { enumerable: true, get: function () { return circle_service_1.CircleService; } });
//# sourceMappingURL=index.js.map